name: Build Develop Branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install server
      run: npm install
      working-directory: /
      
    - name: npm install pm2
      run: npm install pm2 -g
      working-directory: /
      
    - name: start server 
      run: pm2 start index.js
      working-directory: server/
      
    - name: npm install client
      run: npm install
      working-directory: client/
      
    - name: client start
      run: npm start
      working-directory: client/
